### ISSUE TITLE
Unable to scale per process

### ISSUE THREAD

**Issue by alpakpinar** [alpakpinar/vbfml#23]
Currently, the `datasets.yml` interface has the scaling implemented by the `scale` parameter, provided to each class. In several circumstances, this is restrictive since it might mean scaling down the `QCD V` and `EWK V` samples together, and we already have low number of `EWK V` events.

One nicer interface could be to make this scaling interface per process, where each process can be scaled individually, possibly something like:

```yaml
scales:
  qcd_v:
    scale: 0.05
  ewk_v:
    scale: 1
  ...
```

@pmayenco please note, we can make this upgrade in the near-term future.
